model:
  encoder_name: "resnet34"
  encoder_weights: "imagenet"
  in_channels: 3
  classes: 1
dataloader:
  batch_size: 64
  num_workers: 4
  pin_memory: True
dataset:
  metadata_loc: "./data/metadata.json"
  transform: True
  crop_size: 224
  in_channels: 3
  loc: [0.485, 0.456, 0.406]
  scale: [0.229, 0.224, 0.225]
  p_3drot: 0
  