model:
  checkpoint: "microsoft/deberta-base"
  fc_dropout: 0.2
  use_pretrained: True
  config_path:
  output_hidden_states: True
  num_labels: 1
data:
  max_length: 466
  batch_size: 12
  n_folds: 5
  n_workers: 0
train:
  n_epochs: 5
  device: "cuda"
  backbone_lr: 2e-5
  fc_lr: 2e-5
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1e-8
  scheduler_type: "cosine"
  num_warmup_steps: 10
  num_cycles: 0.5
  use_autocast: True
  iters_to_accumulate: 4
  max_gradient_norm: 10
  verbose_step: 1
  